### PR TITLE
Fix climo bounds calculation for 360 day calendar

### PR DESCRIPTION
**Pull request by rod-glover**
This fixes https://github.com/pacificclimate/climate-explorer-backend/issues/34

New annual average climo bound end date is computed as first day of next year instead of end date + 1 day. This is correct so long as the assumption that climatological periods are full years remains correct. Pretty much guaranteed given the definition of monthly climo means.

### CODE REVIEW

**Comment by jameshiebert** [comment]
Sometimes climatologies for hydrologic values are computed based on the "hydrologic calendar", which varies depending on who has defined it. I think that Water Survey Canada uses Oct 1 - Sept 30? So, you may need to be careful with this assumption.

**Comment by rod-glover** [comment]
Hmm. This poses some additional questions/issues:

- Start and end dates for forming the means are currently fixed on Jan 1 boundaries. This apparently needs to be modified to accommodate hydrology.
- What difference, if any, does the hydrologic calendar make to the notion of seasons? (And I just realized we have a slight issue with the winter season on Jan 1-bounded years: The first winter technically begins one month before the start of the specified period, so its mean is necessarily slightly impaired. Fingers crossed that CDO does a sensible thing here and does not divide a 2-month sum by 3 or something.)
- Happily, I think that the "annual" mean -- mean over years of annual mean -- doesn't differ, or differs by vanishingly little. Script calculates it by taking the mean over all values in the climatological period, so the notion of "year" doesn't actually enter into it.

**Comment by rod-glover** [comment]
Met with @mschnorb re. the effect of the "hydrological year" starting on a non-Jan boundary. Conclusion is that the difference this would make to seasonal and annual means is negligibly small and need not be accounted for in our code. Climatological means can safely be taken over 30 year periods that begin and end at Jan 1.

I will add a comment to this effect in the code that calculates begin and end dates.

**Comment by rod-glover** [comment]
Which is in `nchelpers`. I'll add a comment in an appropriate place in this code as well.

**Pull request merged**
