### PR TITLE
Add PEP8 Styling

### PR DESCRIPTION
**Pull request by eyvorchuk**
This PR makes the 20 test files with violations PEP8 compliant.

### CODE REVIEW

**Comment by jameshiebert** [comment]
Did you notice above that the Jenkins tests are failing? Turns out that the Jenkins test run and the Travis test run were *slightly* different (Jenkins was being more thorough).

I've pushed a commit that brings the both in line. Review the Travis output... there are still another 22 source files that need to be `flake8`ified.

**Comment by eyvorchuk** [comment]
The commit I just pushed fixes the Flake8 errors on the 22 source files in question, but `ce/tests/helpers/test_utils.py` still has an `E741 ambiguous variable name 'O'` error. I didn't do anything about this yet because `ce/api/streamflow/watershed.py` uses this variable.

**Comment by jameshiebert** [comment]
Hmmm, I get that too, but it's weird that the test suite does not :shrug:

You can choose to address that if you would like, by coming up with an *unambiguous* variable name that can replace 'O'. `flake8` is right. That variable name is not great in that:

1. It's unclear if it's an Oh or a Zero
1. What does it mean?!

It's *probably* a good idea to fix that. Once you do, this looks ready to merge.

**Comment by eyvorchuk** [comment]
Something like `Out` for outlet?

**Comment by jameshiebert** [comment]
Why abbreviate? `OUTLET` is pretty short already :)

**Pull request merged**
