### PR TITLE
Use m2r2 instead of m2r

### LINKED ISSUE #130: sphinx_build breaks with sphinx > 2.x
I just tried to build the docs on my workstation, which seems to not be working.

```
(ce-venv) james@basalt:~/code/git/climate-explorer-backend$ python setup.py build_sphinx
running build_sphinx
Running Sphinx v3.0.2

Exception occurred:
  File "/tmp/ce-venv/lib/python3.6/site-packages/sphinx/application.py", line 1069, in add_source_parser
    self.registry.add_source_parser(*args, **kwargs)
TypeError: add_source_parser() takes 2 positional arguments but 3 were given
The full traceback has been saved in /tmp/sphinx-err-9aso6dr3.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

After downgrading Sphinx to 2.4.4 the build works, but we can see a deprecation warning that we have apparently been ignoring:

```
(ce-venv) james@basalt:~/code/git/climate-explorer-backend$ python setup.py build_sphinx
running build_sphinx
Running Sphinx v2.4.4
/tmp/ce-venv/lib/python3.6/site-packages/m2r.py:652: RemovedInSphinx30Warning: app.add_source_parser() does not support suffix argument. Use app.add_source_suffix() instead.
  app.add_source_parser('.md', M2RParser)
...
```

I'm not sure where the Markdown parser is configured, so I'm not sure where to point anyone for the solution. @rod-glover , you set this up didn't you?

### PR DESCRIPTION
**Pull request by cairosanders**
This pull request resolves #130 

It looks like m2r is no longer maintained but I found [m2r2](https://pypi.org/project/m2r2/) which is forked off the original m2r repository and it seems to work with sphinx version > 3 although I'm not 100% confident on what the expected output is when you run `python setup.py build_sphinx`...

### CODE REVIEW

**Review by corviday — APPROVED** [review]
I built the documentation in both HTML and PDF, which was a smooth process with a correct result. Looks good!

There were two error messages during the build that were *not* introduced by these changes, but seem to have been revealed by newly improved error checking. They seem pretty minor, would it be possible to correct them as part of this PR? If not, not problem, I'll just make a new PR.

* mismatched single quotes around `attribute=value` on line 4 of `doc/source/api/api-overview.md`; the quotes should both be backticks. Results in a nonsensical link.
* the paragraph that begins "When requesting streamflow data from a point" in `doc/source/workflow.md` has spaces at the beginning of the last few lines of the paragraph. Results in a weird indented section for no discernable reason.

**Comment by cairosanders** [comment]
I can make those changes first thing tomorrow and add them to this pull request

**Comment by corviday** [comment]
Whoops, found one more bit of screwy help formatting, also in `doc/source/workflow.md`. A line begins with "1990. The February timestamp" which is interpreted by m2r2 as a numerical list, like this:

January1990

Sorry for dumping a bunch of unrelated changes on you, thanks for making the helpfile building so much easier!

**Comment by cairosanders** [comment]
I think that should solve the problems

**Review by corviday — APPROVED** [review]
Looks great.

**Pull request merged**
